### ISSUE TITLE
Enable typescript strict mode

### ISSUE THREAD

**Issue by Dassderdie** [alexzuza/ng-run-issue-tracker#1]
To reproduce some typing errors I'd need typescript to run in `strict` mode.

**Comment by alexzuza** [comment]
Hey @Dassderdie,
thank you for reporting this issue.
Can you please share the link to the demo where you're trying to reproduce those typing errors?

**Comment by Dassderdie** [comment]
Sure :)

This is a simple example where I would need strict mode (or strictNullChecks) enabled to reproduce (correct) typing errors:
https://ng-run.com/edit/ip3x4zGu4qcFgCfnJB2M

Maybe it would be best to allow the user to edit the .tsconfig of the project and maybe even the typescript version, because they could be critical for error reproduction too...

**Comment by alexzuza** [comment]
@Dassderdie 
I've exposed some of compilerOptions
![ts](https://user-images.githubusercontent.com/4223314/71528608-1b1c5c80-28fa-11ea-8a40-5b803ce57529.jpg)

Here's a fork of your demo https://ng-run.com/edit/PG8OdlIBrVFIAjEnkpZZ

**Comment by Dassderdie** [comment]
Hi there :)

the typechecking now works in all .ts files as I want it too, but the new typechecking of ivy isn't working in strict mode:
https://ng-run.com/edit/ip3x4zGu4qcFgCfnJB2M?open=app%2Fapp.component.html

I think the following options need to be configureable as well in the `tsconfig.json`
```json
    "angularCompilerOptions": {
        "fullTemplateTypeCheck": true,
        "strictTemplates": true,
        "strictInjectionParameters": true,
        "strictMetadataEmit": true
    }
```
See https://next.angular.io/guide/template-typecheck#strict-mode

**Comment by Dassderdie** [comment]
Oops I think my demo is running as expected. I just have to enable the `ivy-aot`-option...
