### ISSUE TITLE
Error when importing @angular/cdk/drag-drop: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Achilles1515** [alexzuza/ng-run-issue-tracker#12]
I receive the following error when installing `@angular/cdk` and attempting to import the `drag-drop` module.

```
Error in file https://ng-run-preview.firebaseapp.com/d0b0cdecd89f278e9cfe2aaafd6d42ce.sb.js(2:27140)
General error
Cannot read property 'type' of undefined
  Evaluating https://unpkg.com/@angular/cdk@9.2.0/bundles/cdk-scrolling.umd.js
  Evaluating https://unpkg.com/@angular/cdk@9.2.0/scrolling.js
  Evaluating https://unpkg.com/@angular/cdk@9.2.0/bundles/cdk-drag-drop.umd.js
  Evaluating https://unpkg.com/@angular/cdk@9.2.0/drag-drop.js
  Evaluating app/app.module.ts
  Evaluating main.ts
  Loading app
```

[ng-run Demo](https://ng-run.com/edit/ne1qz5buEqGcu6brj0K1)
_(the only file modified is `app.module.ts`)_

**Comment by Achilles1515** [comment]
Hmm. If I directly open up that demo everything works okay.
Try starting from a new ng-run demo and installing `@angular/cdk` and then importing the `DragDropModule`.

**Comment by alexzuza** [comment]
Hey @Achilles1515 
Yes, there was a bug related to compilation of `@angular/cdk` but I fixed it recently.

I double-checked it in a new demo and it works for me

**Comment by Achilles1515** [comment]
> Hey @Achilles1515
> Yes, there was a bug related to compilation of `@angular/cdk` but I fixed it recently.
> 
> I double-checked it in a new demo and it works for me

Sorry for the late reply - looks like this is working now. Thanks for the fix, I'll close the issue.
