### ISSUE TITLE
ES2015 compilation

### ISSUE THREAD

**Issue by waterplea** [alexzuza/ng-run-issue-tracker#2]
Hi Alexey.

I'm working on a library which requires ES2015 support with proper classes, not transpiled ES5 code. Is it possible to enable ES2015 compilation in ng-run? Seems to be impossible with codesandbox or stackblitz with issues open for a while :(

**Comment by alexzuza** [comment]
Hi Alex,

Yes, I added support for it recently

![1](https://user-images.githubusercontent.com/4223314/73607675-8977cd00-45d2-11ea-8ab8-3c972b6fd34d.png)

**Comment by waterplea** [comment]
Great, thanks! I noticed one thing, seems like it also works in Stackblitz when you define your own own tsconfig and set target. It compiles current app to ES2015, but if you import an Angular library, packaged with proper ng-packagr format, it uses ES5 version of it. Might be Angular issue, I wonder if it can be fixed on the IDE side.
