### ISSUE TITLE
External links should provide a confirmation message before navigating

### ISSUE THREAD

**Issue by Achilles1515** [alexzuza/ng-run-issue-tracker#3]
I was working on an ng-run project yesterday (trying to reproduce an Ivy bug) and after 10 minutes of editing, I clicked on "About project" in the lower left corner and was immediately routed to the 'about' page and all my work was lost.

Please provide a confirmation message, similar to StackBlitz, before navigating away.

![image](https://user-images.githubusercontent.com/23387905/73749233-f2715900-4728-11ea-91c2-68c1b13ded5c.png)

**Comment by alexzuza** [comment]
Hey,
Thanks for reporting this issue.
Actually, it worked if you logged in and edit your project.

I added warning for any cases so you can test it.
