### ISSUE TITLE
Ivy AOT: Reloading the preview pane causes infinite loading

### ISSUE THREAD

**Issue by Achilles1515** [alexzuza/ng-run-issue-tracker#4]
With Ivy AOT mode enabled, reloading the preview pane (hitting the refresh/reload button) will sometimes cause the preview pane to be forever stuck in loading mode.

I don't have specific steps, but it should be easily reproducible as it has been happening to me all day.

![image](https://user-images.githubusercontent.com/23387905/73789602-18205180-476d-11ea-8c0b-45c2efc3e0ba.png)

**Comment by Achilles1515** [comment]
@alexzuza Do you have any updates on this issue? It makes it annoying to use Ivy when you just want to "reset" interactions in the preview pane without making modifications to code or refreshing the entire tab.

**Comment by alexzuza** [comment]
@Achilles1515 
Hey, sorry for the delay.
I released a new version with this fix. Can you please try it once again?

**Comment by Achilles1515** [comment]
> Hey, sorry for the delay.
> I released a new version with this fix. Can you please try it once again?

Seems like it works now. Thanks! I'll close this issue.
