### ISSUE TITLE
9.0.0-rc.14 CORS errors in console

### ISSUE THREAD

**Issue by Achilles1515** [alexzuza/ng-run-issue-tracker#5]
Trying to load the following:

https://ng-run.com/edit/tvqV5P78BchpccNmW4XU?open=index.html&aot=true

![image](https://user-images.githubusercontent.com/23387905/73791254-f2e11280-476f-11ea-92c9-8ed6e3415005.png)

**Comment by alexzuza** [comment]
Hi @Achilles1515 
I guess it should work now. It least it works for me

**Comment by Achilles1515** [comment]
Looks like it is working for me now. Thanks!
