### ISSUE TITLE
Go to specific branch on Github project

### ISSUE THREAD

**Issue by NickHodges** [alexzuza/ng-run-issue-tracker#9]
Right now, it appears that all I can do is go to the master branch.  

I'd like a way to specify the branch for my github application being displayed.

**Comment by alexzuza** [comment]
Hey @NickHodges 
Thanks for reporting the issue.

Can you please give me the link to your branch?

**Comment by kievsash** [comment]
Hi, Alex
Here is mine with same issue: https://ng-run.com/github/kievsash/ngrx-store-and5sillyMistakes/tree/pitfall_1_ReduxDevTools_Doesnt_display_undefined?open=src%2Fapp%2Fapp.component.ts
Seems like it loads master branch

Actually tha branch link: https://github.com/kievsash/ngrx-store-and5sillyMistakes/tree/pitfall_1_ReduxDevTools_Doesnt_display_undefined

**Comment by alexzuza** [comment]
@kievsash 
Thanks for the reproduction.
Seems I found the issue on my side and fixed it.
You can try it again

**Comment by kievsash** [comment]
Works now, thank you!
